name: "build"

on:
  pull_request:
    paths-ignore:
      - ".docs/**"
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 8 * * 1"

env:
  extensions: "json"
  cacheVersion: "1"
  composerVersion: "2"
  composerInstall: "composer install"

jobs:
  qa:
    name: "Quality Assurance"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        php-versions: [ "8.4" ]
        operating-system: [ "ubuntu-latest" ]
      fail-fast: false

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "${{ env.extensions }}"
          tools: "composer:${{ env.composerVersion }}"
          cache: "composer"

      - name: "Validate Composer"
        run: "composer validate"

      - name: "Install dependencies"
        run: "${{ env.composerInstall }}"

      - name: "Coding Standard"
        run: "make cs"

  static-analysis:
    name: "Static analysis"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        php-versions: [ "8.4" ]
        operating-system: [ "ubuntu-latest" ]
      fail-fast: false

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "${{ env.extensions }}"
          tools: "composer:${{ env.composerVersion }}"
          cache: "composer"

      - name: "Install dependencies"
        run: "${{ env.composerInstall }}"

      - name: "PHPStan"
        run: "make phpstan"

  tests:
    name: "Tests"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        php-versions: [ "8.4" ]
        operating-system: [ "ubuntu-latest" ]
      fail-fast: false

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "${{ env.extensions }}"
          tools: "composer:${{ env.composerVersion }}"
          cache: "composer"

      - name: "Install dependencies"
        run: "${{ env.composerInstall }}"

      - name: "Tests"
        run: "make tests"
