name: "Tester"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  tester:
    name: "Tester"
    uses: contributte/.github/.github/workflows/tester.yml@v1
    with:
      php: "8.4"
      make: "init tests"
